import bcrypt from 'bcryptjs';

const data = {
  users: [
    {
      name: 'Ash',
      email: 'admin@example.com',
      password: bcrypt.hashSync('1234', 8),
      isAdmin: true,
    },
    {
      name: 'John',
      email: 'user@example.com',
      password: bcrypt.hashSync('1234', 8),
      isAdmin: false,
    },
  ],
  products: [
    {
      name: '007 Lego Car',
      category: 'toy',
      image: '/images/007Car.PNG',
      price: 120,
      countInStock: 10,
      brand: 'Lego',
      rating: 4.5,
      numReviews: 10,
      description: 'For the cool kids. Only 75 of the real $1.2 million McLaren Senna GTR exist, but you can build your own with 830 plastic bricks and celebrate the world of insane track-only hypercars. The 814-hp Senna GTR is lighter, more powerful, and quicker than the already nutty McLaren Senna, and its serrated design looks sharp enough to cut air into slices. The finished Lego Senna GTR measures a foot in length, which is only three inches short of the real Sennas carbon ceramic brakes.'},
    {
      name: 'Aquaman Action Figure',
      category: 'toy',
      image: '/images/AquamanAF.PNG',
      price: 100,
      countInStock: 20,
      brand: 'DC',
      rating: 4.0,
      numReviews: 10,
      description: '100% Toy, Imported, From DC Comics New 52 comics, Based on designs by superstar artist Jim Lee artwork from Justice League Features a new take on the characters classic costume',
    },
    {
      name: 'Batman Action Figure',
      category: 'toy',
      image: '/images/BatmanStrech.PNG',
      price: 220,
      countInStock: 0,
      brand: 'DC',
      rating: 4.8,
      numReviews: 17,
      description: 'Great quality and craftsmanship. It is not designed or intended primarily for children 12 years of age or younger.',
    },
    {
      name: 'Cyborg Action Figure',
      category: 'toy',
      image: '/images/CyborgAF.PNG',
      price: 78,
      countInStock: 15,
      brand: 'DC',
      rating: 4.5,
      numReviews: 14,
      description: 'Designed with Ultra Articulation with up to 22 moving parts for full range of posing and play',
    },
    {
      name: 'Lamborghini Lego',
      category: 'toy',
      image: '/images/Lambo.PNG',
      price: 365,
      countInStock: 5,
      brand: 'Lego',
      rating: 4.5,
      numReviews: 10,
      description: 'Enjoy immersive building with this LEGO Technic Lamborghini Sián FKP 37 set 42115. Then explore the model car’s faithful features, including V12 engine with moving pistons, steering, and front and rear suspension',
    },
    {
      name: 'Lego Bat Mask',
      category: 'toy',
      image: '/images/LegoBatHead.PNG',
      price: 139,
      countInStock: 12,
      brand: 'Lego',
      rating: 4.5,
      numReviews: 15,
      description: 'This LEGO brick recreation of the unmistakable cowl worn by the Caped Crusader™ is sure to attract attention and admiration wherever it is placed. With transparent bricks to represent the face and a stylish fact plaque attached to the sturdy base, this remarkable model will provide a sense of fulfilment long after the construction work has finished',
    },
    {
      name: 'Lego BatJoker',
      category: 'toy',
      image: '/images/LegoBat_jocker.PNG',
      price: 139,
      countInStock: 12,
      brand: 'Lego',
      rating: 4.5,
      numReviews: 15,
      description: 'high quality product',
    },
    {
      name: 'Batmobile',
      category: 'toy',
      image: '/images/Batmobile.PNG',
      price: 139,
      countInStock: 12,
      brand: 'DC',
      rating: 4.5,
      numReviews: 15,
      description: 'high quality product',
    },
    {
      name: 'Electronic',
      category: 'toy',
      image: '/images/Elec.jpg',
      price: 19,
      countInStock: 22,
      brand: 'DC',
      rating: 4.2,
      numReviews: 215,
      description: 'high quality product',
    },
    {
      name: 'Doll',
      category: 'toy',
      image: '/images/Doll.jpg',
      price: 19,
      countInStock: 22,
      brand: 'DC',
      rating: 4.2,
      numReviews: 215,
      description: 'high quality product',
    },
    {
      name: 'ED',
      category: 'toy',
      image: '/images/Ed.jpg',
      price: 19,
      countInStock: 22,
      brand: 'DC',
      rating: 4.2,
      numReviews: 215,
      description: 'high quality product',
    },
    {
      name: 'Mario',
      category: 'toy',
      image: '/images/mario03.png',
      price: 19,
      countInStock: 22,
      brand: 'DC',
      rating: 4.2,
      numReviews: 215,
      description: 'high quality product',
    },
  ],
};
export default data;
